name: Test

on: [push]

jobs:
  Test:
    strategy:
      matrix:
        go-ver: [
          "1.18", "1.19", "1.20"
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-ver }}
      - name: Install dependencies
        run: go mod tidy
      - name: Test
        run: go test -v ./...